### YamlMime:ManagedReference
items:
- uid: System.Runtime.Remoting.RemotingTimeoutException
  id: RemotingTimeoutException
  children:
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RemotingTimeoutException
  nameWithType: RemotingTimeoutException
  fullName: System.Runtime.Remoting.RemotingTimeoutException
  type: Class
  summary: "Unntaket oppstod når serveren eller klienten ikke kan nås for en tidligere angitt tidsrom."
  remarks: "RemotingTimeoutException forårsakes når en ekstern kommunikasjon kall ikke fullføres tidspunkt angitt tidsavbrudd.       RemotingTimeoutException bruker HRESULT COR_E_REMOTING, som har verdien 0x8013150B.       RemotingTimeoutException bruker standard <xref:System.Object.Equals%2A>implementering, som støtter referanse likhet.</xref:System.Object.Equals%2A>       Hvis du vil se en liste med opprinnelige verdier for en forekomst av RemotingTimeoutException, kan du se RemotingTimeoutException konstruktører."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class RemotingTimeoutException : System.Runtime.Remoting.RemotingException
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Runtime.Remoting.RemotingException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor
  id: '#ctor'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException()
  nameWithType: RemotingTimeoutException.RemotingTimeoutException()
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> klasse standardegenskapene."
  remarks: "<xref:System.Runtime.Remoting.RemotingTimeoutException>arver fra <xref:System.Exception>klasse.</xref:System.Exception></xref:System.Runtime.Remoting.RemotingTimeoutException> Tabellen nedenfor viser første egenskapsverdier for en forekomst av klassen <xref:System.Runtime.Remoting.RemotingTimeoutException>: | Egenskapen | Verdien |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| Lokaliserte feilmelding for <xref:System.Runtime.Remoting.RemotingTimeoutException>|</xref:System.Runtime.Remoting.RemotingTimeoutException> </xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException ();
    parameters: []
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException(String)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Initialiserer en ny forekomst av <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> klassen med en angitt melding."
  remarks: "<xref:System.Runtime.Remoting.RemotingTimeoutException>arver fra <xref:System.Exception>klasse.</xref:System.Exception></xref:System.Runtime.Remoting.RemotingTimeoutException> Tabellen nedenfor viser første egenskapsverdier for en forekomst av klassen <xref:System.Runtime.Remoting.RemotingTimeoutException>: | Egenskapstype | Betingelse |   |-------------------|---------------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| Den `message` streng |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Meldingen som angir årsak hvorfor unntaket oppstod."
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException(String,Exception)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> klassen med en angitt feilmelding og en referanse til det interne unntaket er årsaken til dette unntaket."
  remarks: "Et unntak som er registrert som en direkte resultatet av et tidligere unntak må inneholde en referanse til det tidligere unntaket i den <xref:System.Exception.InnerException%2A>egenskapen.</xref:System.Exception.InnerException%2A> Den <xref:System.Exception.InnerException%2A>egenskapen returnerer den samme verdien som er sendt til konstruktøren, eller `null` hvis den <xref:System.Exception.InnerException%2A>egenskapen leverer ikke internt unntak verdien til konstruktøren.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Tabellen nedenfor viser første egenskapsverdier for en forekomst av klassen <xref:System.Runtime.Remoting.RemotingTimeoutException>: | Egenskapen | Verdien |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Internt unntak-referanse |   | <xref:System.Exception.Message%2A>| Feil melding strengen |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException (string message, Exception InnerException);
    parameters:
    - id: message
      type: System.String
      description: "Feilmelding som forklarer hvorfor unntaket."
    - id: InnerException
      type: System.Exception
      description: "Unntaket er årsaken til den gjeldende unntaket. Hvis den `InnerException` -parameteren er ikke <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, oppstår det gjeldende unntaket i en <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokken som behandler det interne unntaket."
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: System.Runtime.Remoting.RemotingException
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException()
  nameWithType: RemotingTimeoutException.RemotingTimeoutException()
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException()
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException(String)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException(String,Exception)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException
  nameWithType: RemotingTimeoutException.RemotingTimeoutException
